// Auto-generated
let project = new Project('mated');

project.addSources('Sources');
project.addAssets("Bundled/**");
project.addLibrary("armory");
project.addLibrary("iron");
project.addLibrary("iron_format");
project.addParameter("--macro include('armory.trait')");
project.addParameter("--macro include('armory.trait.internal')");
project.addParameter('arm.UITrait');
project.addParameter("--macro keep('arm.UITrait')");
project.addParameter('arm.UINodes');
project.addParameter("--macro keep('arm.UINodes')");
project.addParameter('arm.CamBall');
project.addParameter("--macro keep('arm.CamBall')");
project.addParameter('arm.OrbitCamera');
project.addParameter("--macro keep('arm.OrbitCamera')");
project.addParameter('armory.trait.internal.JSScriptAPI');
project.addParameter("--macro keep('armory.trait.internal.JSScriptAPI')");
project.addShaders('build_armorcoat/compiled/ShaderRaws/Material/Material_mesh.frag.glsl');
project.addShaders('build_armorcoat/compiled/ShaderRaws/Material/Material_mesh.vert.glsl');
project.addShaders('build_armorcoat/compiled/ShaderRaws/Material/Material_shadowmap.frag.glsl');
project.addShaders('build_armorcoat/compiled/ShaderRaws/Material/Material_shadowmap.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/blur_edge_pass/blur_edge_pass_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/blur_edge_pass/blur_edge_pass_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/compositor_pass/compositor_pass_Irr_EnvTex_Rad_SSAO_SMAA_CToneFilmic.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/compositor_pass/compositor_pass_Irr_EnvTex_Rad_SSAO_SMAA_CToneFilmic.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/deferred_indirect/deferred_indirect_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/deferred_indirect/deferred_indirect_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/deferred_light/deferred_light_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/deferred_light/deferred_light_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/deferred_light_quad/deferred_light_quad_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/deferred_light_quad/deferred_light_quad_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/smaa_blend_weight/smaa_blend_weight_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/smaa_blend_weight/smaa_blend_weight_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/smaa_edge_detect/smaa_edge_detect_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/smaa_edge_detect/smaa_edge_detect_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/smaa_neighborhood_blend/smaa_neighborhood_blend_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/smaa_neighborhood_blend/smaa_neighborhood_blend_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/ssao_pass/ssao_pass_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/ssao_pass/ssao_pass_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/world/world_Irr_EnvTex_Rad_SSAO_SMAA.frag.glsl');
project.addShaders('build_armorcoat/compiled/Shaders/world/world_Irr_EnvTex_Rad_SSAO_SMAA.vert.glsl');
project.addAssets("build_armorcoat/compiled/ShaderRaws/Material/Material_data.arm");
project.addAssets("build_armorcoat/compiled/Shaders/blur_edge_pass/blur_edge_pass_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/compositor_pass/compositor_pass_Irr_EnvTex_Rad_SSAO_SMAA_CToneFilmic.arm");
project.addAssets("build_armorcoat/compiled/Shaders/deferred_indirect/deferred_indirect_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/deferred_light/deferred_light_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/deferred_light_quad/deferred_light_quad_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/smaa_blend_weight/smaa_blend_weight_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/smaa_edge_detect/smaa_edge_detect_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/smaa_neighborhood_blend/smaa_neighborhood_blend_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/ssao_pass/ssao_pass_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("build_armorcoat/compiled/Shaders/world/world_Irr_EnvTex_Rad_SSAO_SMAA.arm");
project.addAssets("Libraries/armory/Assets/brdf.png");
project.addAssets("Libraries/armory/Assets/noise8.png");
project.addAssets("Libraries/armory/Assets/smaa_area.png");
project.addAssets("Libraries/armory/Assets/smaa_search.png");
project.addAssets("Env/topanda.hdr");
project.addAssets("build_armorcoat/compiled/Assets/Scene.arm");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_irradiance.arm");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_0.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_1.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_2.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_3.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_4.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_5.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_6.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_7.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_8.hdr");
project.addAssets("build_armorcoat/compiled/Assets/envmaps/topanda_radiance_9.hdr");
project.addAssets("build_armorcoat/compiled/Assets/materials/World_material.arm");
project.addAssets("build_armorcoat/compiled/Assets/meshes/mesh_Cube.001.arm");
project.addAssets("build_armorcoat/compiled/Assets/meshes/mesh_Monkey.arm");
project.addAssets("build_armorcoat/compiled/Assets/meshes/mesh_Plane.arm");
project.addAssets("build_armorcoat/compiled/Assets/meshes/mesh_Sphere.arm");
project.addAssets("build_armorcoat/compiled/Assets/renderpaths/armory_default.arm");
project.addAssets("empty.png");
project.addLibrary("zui");
project.addAssets("Libraries/armory/Assets/droid_sans.ttf");
project.addDefine('arm_ui');
project.addDefine("arm_appwh");

resolve(project);
